version: "2.1"

services:
  blog.web:
    image: blog.web
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 80:3000
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js
